---

#
# source: /home/kivilahtio/MMT-JNSKons//PrettyLibExports/Location.csv
# destination: /home/kivilahtio/MMT-JNSKons//config/translationTables/location_id.yaml
#
# This mapping table is used by the module MMT::TranslationTable::LocationId, it defines mappings from location column to Koha's shelving_location

# PrettyLib-termi Sijaintipaikka

# PrettyLibValue, KohaValue
#             Id, Location, Period, UserLevel, Role, Freq
296: branchLoc(,A-A001a)   # A-talo A001alakerta/Harjoitusluokka, 296, 4, 3, 30, 
284: branchLoc(,A-A012)    # , 30, A-talo A012 alakerta/Taina Viinisalo, 12, 284, 3
364: branchLoc(,A-A018/Vi) # , 30, 8, 364, 3, A-talo A018/Viululuokka Hans Lodders
175: branchLoc(,A-A020/Hu) # A-talo A020 Huiliuluokka, 175, 4, 0, 30, 0
125: branchLoc(,A-A103/Te) # A-talo A103/Teorialuokka Jukka Koistinen, 101, 0, 125, , 28

#Yhdistetään => A-talo A106/Apulaisrehtori
382: branchLoc(,A-A106) # 30, 0, A-talo A106/Apulaisrehtori, 3, 2, 382
120: branchLoc(,A-A106) # A-talo A106/Opintosihteeri, 5, 0, 120, 0, 30

298: branchLoc(,A-A107)    # , 30, 4, 298, 0, A-talo A107/Opinto-ohjaaja
275: branchLoc(,A-A109)    # 30, , 3, 3, 275, A-talo A109/Säestysluokka Svetlana Pustoshnaja
291: branchLoc(,A-A110/Se) # A-talo A110/Selloluokka Pertti Leinonen, 5, 291, 3, , 30

# Yhdistetään => A-talo A111/Fagotti- ja oboeluokka
373: branchLoc(,A-A111/Fa) # A-talo A111/Fagottiluokka, 2, 373, 3, 0, 30
315: branchLoc(,A-A111/Ob) # A-talo A111/Oboe Katrharine Freihoff, 4, 315, 3, 0, 30
354: branchLoc(,A-A111)    # 3, 354, 0, A-talo A111, , 30

167: branchLoc(,A-A114/Te) # A-talo A114/Teorialuokka Inga Grigorjeva, 0, 129, 167, 30, 
38:  branchLoc(,A-Oppikh) # 30, 0, A-talo alakerta/Oppilaskunnanhuone, 38, 2, 0
180: branchLoc(,A-B110/Al) # 0, 30, 4, 0, 180, A-talo B110/alttoviulu
360: branchLoc(,A-B111/Se) # A-talo B111/Selloluokka Ville Kivivuori, 24, 3, 360, , 30
212: branchLoc(,A-B113/Sä) # 212, 9, 3, A-talo B113/Säestysluokka Jaroslava Kotorova, 30, 
36:  branchLoc(,A-B114/Pi) # 30, 0, 0, 6, 36, A-talo B114/Pianoluokka Päivi Nylund
204: branchLoc(,A-B215/Pi) # , 30, 9, 204, 3, A-talo B215/Pianoluokka Loikkanen
211: branchLoc(,A-B216/Pi) # A-talo B216/Pianoluokka Otto Korhonen, 9, 3, 211, 0, 30
179: branchLoc(,A-B218/Pi) # , 30, A-talo B218/Pianoluokka Tuulikki Lehtinen, 7, 179, 0
206: branchLoc(,A-B219/Pi) # 30, , 3, 5, 206, A-talo B219/PianoluokkaMargareta Domanska
42:  branchLoc(,A-B221/Pi) # A-talo B221/Pianoluokka Reija Kähkönen, 42, 7, 0, 30, 0
191: branchLoc(,A-B306/Vi) # , 30, 4, 191, 0, A-talo B306/Viululuokka Jarmo Kähkönen
26:  branchLoc(,A-B307/Ki) # 0, 30, A-talo B307/Kitaraluokka Juha Mitjonen, 47, 26, 0
44:  branchLoc(,A-B308/Vi) # 30, 0, A-talo B308/Viululuokka, 0, 2, 44
277: branchLoc(,A-B310/Vi) # 4, 3, 277, A-talo B310/Viululuokka Sakari Tervo, 0, 30
187: branchLoc(,A-B311/Hu) # A-talo B311/Huiluluokka Pekka Mustaniemi, 187, 1, 0, 30, 
47:  branchLoc(,A-B313/Vi) # 30, 0, A-talo B313/Viululuokka Katri Kaihola, 0, 12, 47
159: branchLoc(,A-B314/La) # 30, 0, 0, 45, 159, A-talo B314/Laululuokka Anneli Hynninen
46:  branchLoc(,A-B316/Pu) # 65, 0, 46, A-talo B316/Puhallinluokka Kari Tiussa, 0, 30
300: branchLoc(,A-B317/Kl) # 300, 55, 3, A-talo B317/Klarinettiluokka Eevamaija Mustaniemi, 30, 
157: branchLoc(,A-B319/Pu) # 26, 0, 157, A-talo B319/Puhallinluokka Mika Hirvonen, , 30
282: branchLoc(,A-Henki) # A-talo Henkilökunnan huone, 282, 9, 0, 30, 0
299: branchLoc(,A-Kansl) # 299, 2, 3, A-talo/Kanslia Kaija Reijonmaa, 30, 
371: branchLoc(,A-Kokou) # 0, 30, 4, 371, 3, A-talo/Kokoushuone
61:  branchLoc(,A-Konse) # A-talo/Konserttisali, 0, 16, 61, 0, 30
287: branchLoc(,A-Rehto) # 12, 0, 287, A-talo/Rehtori, 28, 


#korjauksia...
84:  branchLoc(,A-Atk) # 30, 0, Atk-luokka, 16, 84, 0
37:  branchLoc(,A-Pieni) # 30, 0, 13, 0, 37, Auditorio

119: branchLoc(,B-1/Kamu)    # 119, 76, 0, B-talo 1.krs./Kamuluokka, 0, 7
270: branchLoc(,B-206)       # 30, 0, B-talo 206/Hiltunen Lassi, 11, 0, 270
314: branchLoc(,B-208)       # , 30, 3, 15, 314, B-talo 208/Aki Hietala
151: branchLoc(,B-215/Ba)    # B-talo 215/Bassoluokka Lassi Hiltunen, 151, 50, 0, , 30
201: branchLoc(,B-215/Or)    # 30, , B-talo 215/Orkesterin harjoitussali, 201, 27, 0
380: branchLoc(,B-4/AuPieni) # B-Talo 4.krs. Aulan pieni harjoitustila, 380, 2, 0, 0, 30
386: branchLoc(,B-4/KäPieni) # 386, 0, 0, B-talo 4.krs. käytävän pieni luokka, 30, 0
369: branchLoc(,B-4/YkHarj)  # 0, 30, 2, 369, 0, B-talo 4.krs. Yläkerran harjoitustila
273: branchLoc(,B-4/BäKomer) # 30, , B-talo 4.krs./Bändiluokan komero, 273, 15, 3
140: branchLoc(,B-4/Bä)      # 30, , B-talo 4.krs./Bändiluokka, 80, 0, 140
272: branchLoc(,B-4/BäSyve)  # B-talo 4.krs./Bändiluokka syvennys, 272, 4, 3, , 30
381: branchLoc(,B-4/JariKirsi) # 30, 0, 8, 381, 3, B-talo 4.krs./Jari Lappalainen ja Kirsi Uutinen
199: branchLoc(,B-4/Mikko)   # 8, 0, 199, B-talo 4.krs./Mikko Tirronen, 0, 30 
235: branchLoc(,B-4/Rumpu)   # , 30, 57, 235, 3, B-talo 4.krs./Rumpuluokka 2
198: branchLoc(,B-4/Solfa)   # 30, 0, B-talo 4.krs./Solfaluokka (Teoria 2) Emilia Sowah, 198, 15, 0
161: branchLoc(,B-4/Studio)  # 161, 53, 0, B-talo 4.krs./Studio, 30, 
258: branchLoc(,B-4/TePääty) # 30, , B-talo 4.krs./Teorialuokka 1 (päätyluokka), 3, 30, 258
243: branchLoc(,B-405/Ki)    # 12, 3, 243, B-talo 405/Kitaraluokka Vili Paavilainen, 0, 30
289: branchLoc(,B-406/Mi)    # 30, 0, 3, 25, 289, B-talo 406 Midiluokka/Luoma
251: branchLoc(,B-426/Sa)    # 17, 3, 251, B-talo 426/Saksofoniluokka Petri Karttunen, , 30
324: branchLoc(,B-OpetHu)    # 1, 0, 324, B-talo Opettajanhuone 3.krs., , 30
209: branchLoc(,B-Kell)      # B-talo/Kellari, 209, 12, 0, 30,
226: branchLoc(,B-Kell/Ark)  # 226, 112, 0, B-talo/Kellarin arkisto, , 30
217: branchLoc(,C-208/Pi)    # 30, , 7, 3, 217, C-ciipi C208/Pianoluokka Kemal
384: branchLoc(,C-AlaKunto)  # 30, 0, C-siipi alakerta/Kuntosali, 0, 3, 384
216: branchLoc(,C-205/Pi)    # 30, , 2, 216, 3, C-siipi C205/Pianoluokka
39:  branchLoc(,C-209)       # 30, 0, C-siipi C209, 39, 3, 0
185: branchLoc(,C-210/Pi)    # 30, , C-siipi c210/Pianoluokka Sanna Kainulainen, 2, 0, 185
359: branchLoc(,C-211/Te)    # 30, 0, 43, 3, 359, C-siipi C211/Teknologialuokka
377: branchLoc(,C-212)       # 5, 377, 0, C-siipi C212, 30, 0
182: branchLoc(,C-213/La)    # C-siipi C213/Laululuokka Raija Puhakka, 0, 8, 182, 30,
207: branchLoc(,C-214)       # 3, 3, 207, C-siipi C214/ Perätila, 30,
150: branchLoc(,C-Lyömä)     # 0, 233, 150, C-siipi Lyömäsoitinluokka Matti Koponen, 0, 30
259: branchLoc(,C-Kunto)     # 1, 259, 3, C-siipi/Kuntosali, , 30

# Ihmeellinen virhe. Poistetaan.
385: $DELETE # 1, 385, 0, esICS18270240, 0, 30

# korjauksia...
51:  branchLoc(,B-Kantele) # 0, 30, Kanteleluokka Anna-Maija Kekki, 48, 0, 51

241: $DELETE # 241, 1, 0, Konservatorio/Iltapäiväkerho, , 30

351: $DELETE # 30, , Marjo Hämäläinen, 351, 3, 0
1:   branchLoc(,A-Kirj) # 0, 12301, 1, Musiikkikirjasto, 0, 30
337: branchLoc(,A-Kirj/Ee) # , 30, Musiikkikirjasto/Eerolan hylly, 3, 53, 337
214: branchLoc(,A-Kirj/Kä) # 0, , 782, 3, 214, Musiikkikirjasto/Käsikirjasto
293: branchLoc(,A-Kirj/Ka) # 30, , Musiikkikirjasto/Käytävän kaappi, 3, 520, 293

3:   $DELETE # 0, 30, 10, 0, 3, Pianopedagogiikka
379: branchLoc(,Rupla) # 379, 1, 0, Rupla, 0, 30
178: branchLoc(,A-Vahti) # Vahtimestari/Juha Sorsa, 178, 20, 0, , 30


#AMK paikkoja ei tuoda Kohaan vaan ne poistuvat
227: $DELETE # 0, 1, 227, AMK/Pop/jazz-osasto, , 30
326: $DELETE # 326, 6, 3, Karjalantalo/Anni luokka, , 30
336: $DELETE # Karjalantalo/Armas luokka, 7, 3, 336, 30, 
341: $DELETE # Karjalantalo/Bänditilan aula, 28, 341, 3, , 30
331: $DELETE # , 30, 10, 3, 331, Karjalantalo/Ella luokka
335: $DELETE # Karjalantalo/Happo luokka, 3, 4, 335, , 30
345: $DELETE # 30, , Karjalantalo/Jimi, 36, 345, 3
321: $DELETE # Karjalantalo/Käsikirjasto, 95, 321, 3, , 30
330: $DELETE # , 30, 1, 3, 330, Karjalantalo/Otto luokka
323: $DELETE # 323, 119, 3, Karjalantalo/Pop-jazz, 30, 
333: $DELETE # 0, 30, 66, 3, 333, Karjalantalo/Rajakapteenin Pirtti
357: $DELETE # 357, 1, 3, Karjalantalo/Ranka luokka, , 30
329: $DELETE # , 30, Karjalantalo/Repo luokka, 329, 4, 3
334: $DELETE # 17, 3, 334, Karjalantalo/Teppana luokka, 30, 
347: $DELETE # 30, , 3, 23, 347, Karjalantalo/Tsaali
344: $DELETE # Karjalantalo/Tson, 33, 3, 344, , 30
362: $DELETE # 7, 0, 362, Sirkkala Raija Pesonen-Leinonen, 30, 
310: $DELETE # 30, , Tiedepuisto, 27, 310, 0
349: $DELETE # Toonikatalo, 0, 2, 349, 30, 

# Muskareista poistetaan kaikki esineet.
# Kootaan kaikki muu aineisto yhteen yhteiseen muskarisijaintiin, joka siivotaan.
372: JNSKonsa_Muskari_drop_es(,MUSKARI) # branchLoc(,A-talo B110/) # 0, 30, 31, 372, 3, A-talo B110/Muskari
196: JNSKonsa_Muskari_drop_es(,MUSKARI) # branchLoc(,B-talo 113/M) # 196, 643, 0, B-talo 113/Muskari, 30, 
283: JNSKonsa_Muskari_drop_es(,MUSKARI) # branchLoc(,B-talo 113/M) # , 30, 1, 283, 3, B-talo 113/Muskarin välikkö
189: JNSKonsa_Muskari_drop_es(,MUSKARI) # branchLoc(,B-talo 4.krs) # 4, 0, 189, B-talo 4.krs./Musiikkikerho Päivi Eerola, 30,
72:  JNSKonsa_Muskari_drop_es(,MUSKARI) # 0, 30, Enon muskari, 49, 0, 72
231: JNSKonsa_Muskari_drop_es(,MUSKARI) # Hukanhaudan muskari, 231, 58, 0, , 30
378: JNSKonsa_Muskari_drop_es(,MUSKARI) # Karhumäen muskari, 15, 378, 0, 30, 0
230: JNSKonsa_Muskari_drop_es(,MUSKARI) # 30, , 2, 0, 230, Karsikon muskari
224: JNSKonsa_Muskari_drop_es(,MUSKARI) # Kontiolahden muskari, 16, 224, 0, , 30
229: JNSKonsa_Muskari_drop_es(,MUSKARI) # Lehmon muskari, 229, 90, 0, , 30
319: JNSKonsa_Muskari_drop_es(,MUSKARI) # Niittylahden muskari, 52, 319, 0, 30, 
233: JNSKonsa_Muskari_drop_es(,MUSKARI) # Noljakan muskari, 57, 233, 0, , 30
239: JNSKonsa_Muskari_drop_es(,MUSKARI) # 30, , Onttolan muskari, 239, 46, 0
228: JNSKonsa_Muskari_drop_es(,MUSKARI) # 228, 4, 0, Rantakylän muskari, 30, 



_DEFAULT_: warning()
